package errors

var (
	ErrorsRegexp = map[string][]string{
		"MySQL": []string{
			"SQL syntax.*?MySQL",
			"Warning.*?\\Wmysqli?_",
			"MySQLSyntaxErrorException",
			"valid MySQL result",
			"check the manual that (corresponds to|fits) your MySQL server version",
			"check the manual that (corresponds to|fits) your MariaDB server version",
			"check the manual that (corresponds to|fits) your Drizzle server version",
			"Unknown column '[^ ]+' in 'field list'",
			"MySqlClient\\.",
			"com\\.mysql\\.jdbc",
			"Zend_Db_(Adapter|Statement)_Mysqli_Exception",
			"Pdo[./_\\\\]Mysql",
			"MySqlException",
			"SQLSTATE\\[\\d+\\]: Syntax error or access violation",
			"MemSQL does not support this type of query",
			"is not supported by MemSQL",
			"unsupported nested scalar subselect",
		},
		"PostgreSQL": []string{
			"PostgreSQL.*?ERROR",
			"Warning.*?\\Wpg_",
			"valid PostgreSQL result",
			"Npgsql\\.",
			"PG::SyntaxError:",
			"org\\.postgresql\\.util\\.PSQLException",
			"ERROR:\\s\\ssyntax error at or near",
			"ERROR: parser: parse error at or near",
			"PostgreSQL query failed",
			"org\\.postgresql\\.jdbc",
			"Pdo[./_\\\\]Pgsql",
			"PSQLException",
		},
		"Microsoft SQL Server": []string{
			"Driver.*? SQL[\\-\\_\\ ]*Server",
			"OLE DB.*? SQL Server",
			"\\bSQL Server[^<\"]+Driver",
			"Warning.*?\\W(mssql|sqlsrv)_",
			"\\bSQL Server[^<\"]+[0-9a-fA-F]{8}",
			"System\\.Data\\.SqlClient\\.(SqlException|SqlConnection\\.OnError)",
			"(?s)Exception.*?\\bRoadhouse\\.Cms\\.",
			"Microsoft SQL Native Client error '[0-9a-fA-F]{8}",
			"\\[SQL Server\\]",
			"ODBC SQL Server Driver",
			"ODBC Driver \\d+ for SQL Server",
			"SQLServer JDBC Driver",
			"com\\.jnetdirect\\.jsql",
			"macromedia\\.jdbc\\.sqlserver",
			"Zend_Db_(Adapter|Statement)_Sqlsrv_Exception",
			"com\\.microsoft\\.sqlserver\\.jdbc",
			"Pdo[./_\\\\](Mssql|SqlSrv)",
			"SQL(Srv|Server)Exception",
			"Unclosed quotation mark after the character string",
		},
		"Microsoft Access": []string{
			"Microsoft Access (\\d+ )?Driver",
			"JET Database Engine",
			"Access Database Engine",
			"ODBC Microsoft Access",
			"Syntax error \\(missing operator\\) in query expression",
		},
		"Oracle": []string{
			"\\bORA-\\d{5}",
			"Oracle error",
			"Oracle.*?Driver",
			"Warning.*?\\W(oci|ora)_",
			"quoted string not properly terminated",
			"SQL command not properly ended",
			"macromedia\\.jdbc\\.oracle",
			"oracle\\.jdbc",
			"Zend_Db_(Adapter|Statement)_Oracle_Exception",
			"Pdo[./_\\\\](Oracle|OCI)",
			"OracleException",
		},
		"IBM DB2": []string{
			"CLI Driver.*?DB2",
			"DB2 SQL error",
			"\\bdb2_\\w+\\(",
			"SQLCODE[=:\\d, -]+SQLSTATE",
			"com\\.ibm\\.db2\\.jcc",
			"Zend_Db_(Adapter|Statement)_Db2_Exception",
			"Pdo[./_\\\\]Ibm",
			"DB2Exception",
			"ibm_db_dbi\\.ProgrammingError",
		},
		"Informix": []string{
			"Warning.*?\\Wifx_",
			"Exception.*?Informix",
			"Informix ODBC Driver",
			"ODBC Informix driver",
			"com\\.informix\\.jdbc",
			"weblogic\\.jdbc\\.informix",
			"Pdo[./_\\\\]Informix",
			"IfxException",
		},
		"Firebird": []string{
			"Dynamic SQL Error",
			"Warning.*?\\Wibase_",
			"org\\.firebirdsql\\.jdbc",
			"Pdo[./_\\\\]Firebird",
		},
		"SQLite": []string{
			"SQLite/JDBCDriver",
			"SQLite\\.Exception",
			"(Microsoft|System)\\.Data\\.SQLite\\.SQLiteException",
			"Warning.*?\\W(sqlite_|SQLite3::)",
			"\\[SQLITE_ERROR\\]",
			"SQLite error \\d+:",
			"sqlite3.OperationalError:",
			"SQLite3::SQLException",
			"org\\.sqlite\\.JDBC",
			"Pdo[./_\\\\]Sqlite",
			"SQLiteException",
		},
		"SAP MaxDB": []string{
			"SQL error.*?POS([0-9]+)",
			"Warning.*?\\Wmaxdb_",
			"DriverSapDB",
			"-3014.*?Invalid end of SQL statement",
			"com\\.sap\\.dbtech\\.jdbc",
			"\\[-3008\\].*?: Invalid keyword or missing delimiter",
		},
		"Sybase": []string{
			"Warning.*?\\Wsybase_",
			"Sybase message",
			"Sybase.*?Server message",
			"SybSQLException",
			"Sybase\\.Data\\.AseClient",
			"com\\.sybase\\.jdbc",
		},
		"Ingres": []string{
			"Warning.*?\\Wingres_",
			"Ingres SQLSTATE",
			"Ingres\\W.*?Driver",
			"com\\.ingres\\.gcf\\.jdbc",
		},
		"FrontBase": []string{
			"Exception (condition )?\\d+\\. Transaction rollback",
			"com\\.frontbase\\.jdbc",
			"Syntax error 1. Missing",
			"(Semantic|Syntax) error [1-4]\\d{2}\\.",
		},
		"HSQLDB": []string{
			"Unexpected end of command in statement \\[",
			"Unexpected token.*?in statement \\[",
			"org\\.hsqldb\\.jdbc",
		},
		"H2": []string{
			"org\\.h2\\.jdbc",
			"\\[42000-192\\]",
		},
		"MonetDB": []string{
			"![0-9]{5}![^\\n]+(failed|unexpected|error|syntax|expected|violation|exception)",
			"\\[MonetDB\\]\\[ODBC Driver",
			"nl\\.cwi\\.monetdb\\.jdbc",
		},
		"Apache Derby": []string{
			"Syntax error: Encountered",
			"org\\.apache\\.derby",
			"ERROR 42X01",
		},
		"Vertica": []string{
			", Sqlstate: (3F|42).{3}, (Routine|Hint|Position):",
			"/vertica/Parser/scan",
			"com\\.vertica\\.jdbc",
			"org\\.jkiss\\.dbeaver\\.ext\\.vertica",
			"com\\.vertica\\.dsi\\.dataengine",
		},
		"Mckoi": []string{
			"com\\.mckoi\\.JDBCDriver",
			"com\\.mckoi\\.database\\.jdbc",
			"<REGEX_LITERAL>",
		},
		"Presto": []string{
			"com\\.facebook\\.presto\\.jdbc",
			"io\\.prestosql\\.jdbc",
			"com\\.simba\\.presto\\.jdbc",
			"UNION query has different number of fields: \\d+, \\d+",
		},
		"Altibase": []string{
			"com\\.mimer\\.jdbc",
			"Syntax error,[^\\n]+assumed to mean",
		},
		"CrateDB": []string{
			"io\\.crate\\.client\\.jdbc",
		},
		"Cache": []string{
			"encountered after end of query",
			"A comparison operator is required here",
		},
		"Raima Database Manager": []string{
			"-10048: Syntax error",
			"rdmStmtPrepare\\(.+?\\) returned",
		},
		"Virtuoso": []string{
			"SQ074: Line \\d+:",
			"SR185: Undefined procedure",
			"SQ200: No table",
			"Virtuoso S0002 Error",
			"\\[(Virtuoso Driver|Virtuoso iODBC Driver)\\]\\[Virtuoso Server\\]",
		},
	}
)
